#!/usr/bin/env python3

import sys
import os
import requests
import subprocess
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

path = sys.argv[1]

base_url = "https://repository.mdh.quantum.com:8443/repository/symbols"
    
session = requests.Session()

retries = Retry(total=10,
                backoff_factor=0.1,
                status_forcelist=[500, 502, 503, 504])

session.mount('http://', HTTPAdapter(max_retries=retries))

print("Checking " + path + " for binaries...")

for entry in os.listdir(path):
    fullpath = os.path.join(path, entry)

    print("Dumping symbols from " + fullpath + "...")

    try:

        syms = subprocess.check_output("/opt/quantum/breakpad/bin/dump_syms " + fullpath + " 2>/dev/null",
                                       shell=True, universal_newlines=True)

        header_line = syms.splitlines()[0]
        header = header_line.split()

        sym_id = header[3]

        url = base_url + "/"
        for i in range(0, len(sym_id), 2):
            url += sym_id[i:i+2] + "/"

        url += sym_id

        print("Uploading to " + url + "...")

        response = session.put(url, data=syms)

        if response.status_code != 200 and response.status_code != 201:
            print("Failed to upload symbols for " + fullpath)

    except subprocess.CalledProcessError:
        print("Could not dump symbols from " + fullpath)

    except Exception:
        # If HTTP requests fail just let it go
        pass
